<?php
/**
 * Implements hook_menu().
 */

function custom_cmis_block_info() {
    global $user;
    $account = user;
    $blocks['custom_cmis'] = array('info' => t('Custom Block'));
    return $blocks;
}

function custom_cmis_block_view($delta = ''){
    global $user;
    $account = $user;
    //$uri = str_replace('/alfresco/', '', parse_url($_SERVER['REQUEST_URI'])['path']);
    //$uri = str_replace('-', ' ', $uri);
    //$uri = ucwords($uri);
    $list = listFolders();
    $message = "<ul>";
    $reference = "";
    foreach($list as $obj) {
        $message .= "<li><a href='".$obj->content."'>";
        $message .= $obj->properties['cmis:name'];
        $message .= "</a></li>";
    }
    $message .= "</ul>";
    $block['content'] = $message;
    return $block;
}

function listFolders() {
    require_once "Alfresco_CMIS_API.php";
    $repoUrl="http://alfresco.luke-berry.co.uk:8080/alfresco/cmisatom";
    $username="admin";
    $password="admin";
    $path="/Sites/burtons-demo/documentLibrary/Burtons/taxonomy";

    //Load folder
    $folder= new CMISalfObject($repoUrl,$username,$password,null,null,$path);
    if(!$folder->loaded) die("\nSORRY! cannot open folder!\nThe last HTTP request returned the following status: ".$folder->lastHttpStatus."\n\n" . $folderInc);

    $folder->listContent();
    $folder->goGet();

    $list = array();

    foreach($folder->containedObjects as $obj){
        $type =  (string)$obj->properties['cmis:objectTypeId'];
        if($type == "cmis:folder")
        {
            //echo $obj->properties['cmis:name']." (".$obj->properties['cmis:baseTypeId'].")\n";
            array_push($list, $obj);
        }
    }
    return $list;
}
